language: scala
scala:
   - 2.12.12
   - 2.13.1
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
jdk:
  - openjdk11
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
after_success:
  - sbt coveralls